apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  volumes:
  - name: mysitedb
    persistentVolumeClaim:
      claimName: postdb
  containers:
  - name: mysite
    image: docker.io/postgres:14.2
    imagePullPolicy: Always
    volumeMounts:
    - name: mysitedb
      mountPath: /var/lib/postgresql
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_DB
      value: "mysitedb"
    - name: POSTGRES_USER
      value: "mysiteuser"
    - name: POSTGRES_PASSWORD
      value: "mysitepassword"


    